# channels:
#   - conda-forge
# dependencies:
#   - ffmpeg=4.3.1

name: your_environment_name
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ffmpeg    # Install ffmpeg using conda
  - pip:
    - streamlit==1.5.0
    - googletrans==4.0.0-rc1
    - pydub==0.25.1
    - torch==2.2.0
    - TTS==0.21.3
    - speech_recognition


